#server:
#  port: 8081
#spring:
#  application:
#    name: service-acl
#  datasource:
#    password: 123456
#    username: root
#    url: jdbc:mysql://localhost:3306/acldb?serverTimezone=GMT%2B8
#  redis:
#    host: xxxxxxxxxx
#    password: xxxxxxxxxx
#    connect-timeout: 1800000
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: 1
#        max-idle: 5
#        min-idle: 0
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#mybatis-plus:
#  mapper-locations: classpath:com/xlkk/aclservice/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
#
#
#
